---
language: ruby
cache: bundler
services:
   - postgresql
   - redis
rvm:
  - 2.6.1
before_install: gem install bundler -v 2.1.4
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - bundle exec rspec
  - bundle exec rubocop
