---
language: ruby
cache: bundler
services:
   - postgresql
rvm:
  - 2.6.1
before_install: gem install bundler -v 2.1.4
before_script:
  - cp config/database.yml.travis config/database.yml
  - rake db:create
  - rake db:migrate
script:
  - bundle exec rspec
  - bundle exec rubocop
